name: Install python dependencies
description: Setup python packages and requirements

runs:
  using: composite
  steps:
    - name: Setup python additional packages
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel coveralls

    - name: Install requirements
      shell: bash
      run: pip install -r requirements.txt