name: Run tests
description: Run all required tests

runs:
  using: composite
  steps:
    - name: Run flake8 checks
      shell: bash
      run: flake8 inspire_json_merger tests

    - name: Run pytest
      shell: bash
      run: pytest tests/
